; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
build_flags =
  -D IOT_NODE_PIO_ENV=$PIOENV
  -D IOT_NODE_PIO_PLATFORM=$PIOPLATFORM
  -D IOT_NODE_PIO_FRAMEWORK=$PIOFRAMEWORK
  ; -D IOT_NODE_AP_ALGORE
  ; -D IOT_NODE_AP_ELZAR
  ; -D IOT_NODE_AP_RICHARDNIXON
  ; -D IOT_NODE_AP_SPIROAGNEW
  ; -D IOT_NODE_DHCP
  ; -D IOT_NODE_DEFER_INITIAL_LOGGING
  !echo "-D IOT_NODE_BUILD_GIT_REV="$(git rev-parse HEAD)
lib_deps =
  me-no-dev/ESPAsyncUDP @ 0.0.0-alpha+sha.697c75a025

[env:esp01_1m]
platform = espressif8266
board = esp01_1m
board_build.filesystem = littlefs
monitor_speed = 74880
