[template]
build_flags = 
	; default
	!echo "-D IOT_NODE_BUILD_GIT_REV="$(git rev-parse HEAD)
	-D IOT_NODE_PIO_ENV=$PIOENV
	-D IOT_NODE_PIO_PLATFORM=$PIOPLATFORM
	-D IOT_NODE_PIO_FRAMEWORK=$PIOFRAMEWORK
	-D ARDUINO_SAMD_VARIANT_COMPLIANCE
	; io-management
	-D RX1=35
	-D TX1=4
	-D RX2=36
	-D TX2=14
	; ip
	-D IOT_NODE_DHCP
	; link
	-D IOT_NODE_LINK_ETH
	-D IOT_NODE_WT32_ETH01
  ; wifi
  -D IOT_NODE_WIFI_SSID="legacy.wifi.wurstsalat.cloud"
  -D IOT_NODE_WIFI_PSK="xyz"
  -D IOT_NODE_AP_ALGORE
  -D IOT_NODE_AP_ELZAR
  -D IOT_NODE_AP_RICHARDNIXON
  -D IOT_NODE_AP_SPIROAGNEW
	; i2c-scan
	-D IOT_NODE_I2C_SCAN
	; sensors
	-D IOT_NODE_BME280
  -D IOT_NODE_CCS811
  -D IOT_NODE_MCP9808
  -D IOT_NODE_MHZ19
  -D IOT_NODE_SDS011
  -D IOT_NODE_SGP30
  -D IOT_NODE_TSL2561
  -D IOT_NODE_VEML6070
