; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
build_flags = 
	-D IOT_NODE_PIO_ENV=$PIOENV
	-D IOT_NODE_PIO_PLATFORM=$PIOPLATFORM
	-D IOT_NODE_PIO_FRAMEWORK=$PIOFRAMEWORK
	-D IOT_NODE_DHCP
  -D IOT_NODE_LINK_ETH
	-D IOT_NODE_WIFI_SSID="legacy.wifi.wurstsalat.cloud"
	-D IOT_NODE_WIFI_PSK="xyz"
	!echo "-D IOT_NODE_BUILD_GIT_REV="$(git rev-parse HEAD)

[env:esp8266]
platform = espressif8266
board = esp01_1m
board_build.filesystem = littlefs
monitor_speed = 74880
lib_deps = me-no-dev/ESPAsyncUDP

[env:esp32]
platform = espressif32
board = esp32-poe
board_build.filesystem = littlefs
monitor_speed = 115200
