; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
upload_port = socket://serial.net.wurstsalat.cloud:23
monitor_port = socket://serial.net.wurstsalat.cloud:23
build_flags = 
	-D IOT_NODE_PIO_ENV=$PIOENV
	-D IOT_NODE_PIO_PLATFORM=$PIOPLATFORM
	-D IOT_NODE_PIO_FRAMEWORK=$PIOFRAMEWORK
	-D ARDUINO_SAMD_VARIANT_COMPLIANCE
	-D IOT_NODE_DHCP
	-D IOT_NODE_LINK_ETH
	-D IOT_NODE_WT32_ETH01
	-D IOT_NODE_BME280
	-D IOT_NODE_MCP9808
	-D IOT_NODE_SGP30
	-D IOT_NODE_TSL2561
	!echo "-D IOT_NODE_BUILD_GIT_REV="$(git rev-parse HEAD)

[env:esp8266]
platform = espressif8266
board = esp01_1m
board_build.filesystem = littlefs
monitor_speed = 74880
upload_speed = 74880
lib_deps = 
	adafruit/Adafruit BME280 Library@^2.1.2
	adafruit/Adafruit BusIO@^1.7.2
	adafruit/Adafruit MCP9808 Library@^1.1.2
	adafruit/Adafruit SGP30 Sensor@^2.0.0
	adafruit/Adafruit TSL2561@^1.1.0
	adafruit/Adafruit Unified Sensor@^1.1.4
	adafruit/Adafruit VEML6070 Library@^1.0.4
	lewapek/Nova Fitness Sds dust sensors library@^1.5.0
	me-no-dev/ESPAsyncUDP
	sparkfun/SparkFun CCS811 Arduino Library@^2.0.1
	wifwaf/MH-Z19@^1.5.3

[env:esp32]
platform = espressif32@3.0.0
board = esp32dev
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 115200
lib_deps = 
	adafruit/Adafruit BME280 Library@^2.1.2
	adafruit/Adafruit BusIO@^1.7.2
	adafruit/Adafruit MCP9808 Library@^1.1.2
	adafruit/Adafruit SGP30 Sensor@^2.0.0
	adafruit/Adafruit TSL2561@^1.1.0
	adafruit/Adafruit Unified Sensor@^1.1.4
	adafruit/Adafruit VEML6070 Library@^1.0.4
	lewapek/Nova Fitness Sds dust sensors library@^1.5.0
	sparkfun/SparkFun CCS811 Arduino Library@^2.0.1
	wifwaf/MH-Z19@^1.5.3
