[tmp]
	build_flags_tmp_0 =
		; -D IOT_NODE_LOGGING

	; TEMPLATE

	; ; Device-Name
	; ota_host = 0.0.0.0
	; ota_password = xyz
	; name = Test_Device
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	; link
	; 	; -D IOT_NODE_LINK_ETH
	; 	; -D IOT_NODE_LINK_WIFI
	; 	; wifi:ap-pinning
	; 	; -D IOT_NODE_AP_ALGORE
	; 	; -D IOT_NODE_AP_ELZAR
	; 	; -D IOT_NODE_AP_RICHARDNIXON
	; 	; -D IOT_NODE_AP_SPIROAGNEW
	; 	; ip
	; 	; -D IOT_NODE_IP="10, 97, 0, 198"
	; 	; -D IOT_NODE_GATEWAY="10, 97, 0, 1"
	; 	; -D IOT_NODE_NETMASK="255, 255, 255, 0"
	; 	; i2c
	; 	; -D IOT_NODE_I2C_SCAN
	; 	; boards
	; 	; -include "include/boards/..."

	; TESTBED DEVICES

	; ; Test-Device
	; ota_host = test-device.iot-ng.lan.wurstsalat.cloud
	; name = Test-Device
	; board = esp32dev
	; flash_mode = dio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_ETH
	; 	-include "include/boards/Test-Device.h"

	; ; Shelly1
	; ota_host = shelly1.iot-ng.lan.wurstsalat.cloud
	; name = Shelly1
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly1.h"

	; ; Obi-Jack
	; ota_host = obi-jack.iot-ng.lan.wurstsalat.cloud
	; name = Obi-Jack
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Obi-Jack.h"

	; ; H801
	; ota_host = h801.iot-ng.lan.wurstsalat.cloud
	; name = H801
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/H801.h"

	; ; Shelly i3
	; ota_host = shelly-i3.iot-ng.lan.wurstsalat.cloud
	; name = Shelly_i3
	; board = esp01_1m
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly_i3.h"
	
	; ; Olimex ESP32-PoE
	; ota_host = olimex-esp32-poe.iot-ng.lan.wurstsalat.cloud
	; name = Olimex_ESP32-PoE
	; board = esp32dev
	; flash_mode = dio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_ETH
	; 	-include "include/boards/Olimex_ESP32-PoE.h"

	; ; ESP-Now Test-Button
	; ota_host = esp-now-test-button.iot-ng.lan.wurstsalat.cloud
	; name = ESP-Now_Test-Button
	; board = esp8285
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/ESP-Now_Test-Button.h"

	; ; Olimex ESP32-Gateway
	; ota_host = olimex-esp32-gateway.iot-ng.lan.wurstsalat.cloud
	; name = Olimex_ESP32-Gateway
	; board = esp32dev
	; flash_mode = dio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_ETH
	; 	-include "include/boards/Olimex_ESP32-Gateway.h"

	; ; ESP-Now Test-Window-Sensor
	; ota_host = esp-now-test-window-sensor.iot-ng.lan.wurstsalat.cloud
	; name = ESP-Now_Test-Window-Sensor
	; board = esp8285
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/ESP-Now_Test-Window-Sensor.h"

	; ; ESP-Now Test-Button-II
	; ota_host = 0.0.0.0
	; name = ESP-Now_Test-Button-II
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/ESP-Now_Test-Button-II.h"

	; ; LilyGo 4.7 inch e-paper
	; ota_host = lilygo-e-paper.iot-ng.lan.wurstsalat.cloud
	; name = LilyGo-E-Paper
	; board = esp32dev
	; flash_mode = dio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-D BOARD_HAS_PSRAM
	; 	-include "include/boards/LilyGo-E-Paper.h"

	; ; wireless-tag WT32-SC01
	; ota_host = wt32-sc01.iot-ng.lan.wurstsalat.cloud
	; name = WT32-SC01
	; board = esp32dev
	; flash_mode = dio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-D BOARD_HAS_PSRAM
	; 	-include "include/boards/WT32-SC01.h"

	; ; Sonoff Basic R2-v1.3
	; ota_host = sonoff-basic.iot-ng.lan.wurstsalat.cloud
	; name = Sonoff_Basic
	; board = esp8285
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Sonoff_Basic_R2V13.h"

	; REAL WORLD DEVICES

	; ; Shelly1, storage, ceilingLight
	; ota_host = storage-ceilinglight.iot.wurstsalat.cloud
	; name = storage-ceilingLight
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly1.h"

	; ; Sonoff Basic R2-v1.3, office, ceilingLight
	; ota_host = office-ceilinglight.iot.wurstsalat.cloud
	; name = office-ceilingLight
	; board = esp8285
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Sonoff_Basic_R2V13.h"

	; ; H801, office, workbenchLEDs
	; ota_host = office-workbenchleds.iot.wurstsalat.cloud
	; name = office-workbenchLEDs
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/H801.h"

	; ; Obi-Jack, office, floodlight
	; ota_host = office-floodlight.iot.wurstsalat.cloud
	; name = office-floodlight
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Obi-Jack.h"

	; ; Shelly i3, office, wallSwitch
	; ota_host = office-wallswitch.iot.wurstsalat.cloud
	; name = office-wallSwitch
	; board = esp01_1m
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly_i3.h"

	; ; Obi-Jack, livingRoom, standingLamp
	; ota_host = livingroom-standinglamp.iot.wurstsalat.cloud
	; name = livingRoom-standingLamp
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Obi-Jack.h"

	; ; Obi-Jack, diningRoom, standingLamp
	; ota_host = diningroom-standinglamp.iot.wurstsalat.cloud
	; name = diningRoom-standingLamp
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Obi-Jack.h"

	; ; Shelly1, bedroom, ceilingLight
	; ota_host = bedroom-ceilinglight.iot.wurstsalat.cloud
	; name = bedroom-ceilingLight
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly1.h"

	; ; Obi-Jack, bedroom, stoneLamp
	; ota_host = bedroom-stonelamp.iot.wurstsalat.cloud
	; name = bedroom-stoneLamp
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Obi-Jack.h"

	; ; H801, bedroom, bedRGBWLEDs
	; ota_host = bedroom-bedrgbwleds.iot.wurstsalat.cloud
	; name = bedroom-bedRGBWLEDs
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/H801.h"

	; ; H801, bedroom, nightstandLEDs
	; ota_host = bedroom-nightstandleds.iot.wurstsalat.cloud
	; name = bedroom-nightstandLEDs
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/H801.h"

	; ; Shelly i3, bedroom, wallSwitchDoor
	; ota_host = bedroom-wallswitchdoor.iot.wurstsalat.cloud
	; name = bedroom-wallSwitchDoor
	; board = esp01_1m
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly_i3.h"

	; ; Obi-Jack, livingRoom, fan
	; ota_host = livingroom-fan.iot.wurstsalat.cloud
	; name = livingRoom-fan
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Obi-Jack.h"

	; ; Shelly i3, livingRoom, wallSwitch
	; ota_host = livingroom-wallswitch.iot.wurstsalat.cloud
	; name = livingRoom-wallSwitch
	; board = esp01_1m
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly_i3.h"

	; ; Sonoff Basic R2-v1.3, livingRoom, ceilingLight
	; ota_host = livingroom-ceilinglight.iot.wurstsalat.cloud
	; name = livingRoom-ceilingLight
	; board = esp8285
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Sonoff_Basic_R2V13.h"

	; ; Sonoff Basic R2-v1.3, diningRoom, ceilingLight
	; ota_host = diningroom-ceilinglight.iot.wurstsalat.cloud
	; name = diningRoom-ceilingLight
	; board = esp8285
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Sonoff_Basic_R2V13.h"

	; ; Sonoff Basic R2-v1, diningRoom, tableLight
	; ota_host = diningroom-tablelight.iot.wurstsalat.cloud
	; name = diningRoom-tableLight
	; board = esp8285
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Sonoff_Basic_R2V1.h"

	; ; H801, diningRoom, kallaxLEDs
	; ota_host = diningroom-kallaxleds.iot.wurstsalat.cloud
	; name = diningRoom-kallaxLEDs
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/H801.h"

	; ; Shelly i3, diningRoom, wallSwitch
	; ota_host = diningroom-wallswitch.iot.wurstsalat.cloud
	; name = diningRoom-wallSwitch
	; board = esp01_1m
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly_i3.h"

	; ; H801, kitchen, LEDsRight
	; ota_host = kitchen-ledsright.iot.wurstsalat.cloud
	; name = kitchen-LEDsRight
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/H801.h"

	; ; H801, kitchen, LEDsLeft
	; ota_host = kitchen-ledsleft.iot.wurstsalat.cloud
	; name = kitchen-LEDsLeft
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/H801.h"

	; ; Obi-Jack, diningRoom, fan
	; ota_host = diningroom-fan.iot.wurstsalat.cloud
	; name = diningRoom-fan
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Obi-Jack.h"

	; ; Shelly1, hallway, ceilingLightFront
	; ota_host = hallway-ceilinglightfront.iot.wurstsalat.cloud
	; name = hallway-ceilingLightFront
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly1.h"

	; ; Sonoff Basic R2-v1.3, hallway, ceilingLightBack
	; ota_host = hallway-ceilinglightback.iot.wurstsalat.cloud
	; name = hallway-ceilingLightBack
	; board = esp8285
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Sonoff_Basic_R2V13.h"

	; ; Shelly1, showerBathroom, ceilingLight
	; ota_host = showerbathroom-ceilinglight.iot.wurstsalat.cloud
	; name = showerBathroom-ceilingLight
	; board = esp01_1m
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly1.h"

	; ; Shelly1, bathtubBathroom, ceilingLight
	; ota_host = bathtubbathroom-ceilinglight.iot.wurstsalat.cloud
	; name = bathtubBathroom-ceilingLight
	; board = esp01_1m
	; flash_mode = qio
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly1.h"

	; ; Shelly i3, kitchen, wallSwitchFront
	; ota_host = kitchen-wallswitchfront.iot.wurstsalat.cloud
	; name = kitchen-wallSwitchFront
	; board = esp01_1m
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly_i3.h"

	; ; Shelly i3, kitchen, wallSwitchBack
	; ota_host = kitchen-wallswitchback.iot.wurstsalat.cloud
	; name = kitchen-wallSwitchBack
	; board = esp01_1m
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly_i3.h"

	; ; Shelly i3, bathtubBathroom, wallSwitchMirror
	; ota_host = bathtubbathroom-wallswitchmirror.iot.wurstsalat.cloud
	; name = bathtubBathroom-wallSwitchMirror
	; board = esp01_1m
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly_i3.h"

	; ; Shelly i3, showerBathroom, wallSwitchDoor
	; ota_host = showerbathroom-wallswitchdoor.iot.wurstsalat.cloud
	; name = showerBathroom-wallSwitchDoor
	; board = esp01_1m
	; flash_mode = dout
	; build_flags_tmp_1 =
	; 	-D IOT_NODE_LINK_WIFI
	; 	-include "include/boards/Shelly_i3.h"
