[tmp]
	ota_host = 0.0.0.0
	ota_password = xyz
	name = Test_Device
	; board = esp01_1m
	; board_build.flash_mode = dout
	build_flags_tmp_0 =
		; -D IOT_NODE_LOGGING
	build_flags_tmp_1 =
		; link
		; -D IOT_NODE_LINK_ETH
		; -D IOT_NODE_LINK_WIFI
		; wifi:ap-pinning
		; -D IOT_NODE_AP_ALGORE
		; -D IOT_NODE_AP_ELZAR
		; -D IOT_NODE_AP_RICHARDNIXON
		; -D IOT_NODE_AP_SPIROAGNEW
		; ip
		; -D IOT_NODE_IP="10, 97, 0, 198"
		; -D IOT_NODE_GATEWAY="10, 97, 0, 1"
		; -D IOT_NODE_NETMASK="255, 255, 255, 0"
		; i2c
		; -D IOT_NODE_I2C_SCAN
		; boards
		; -include "include/boards/h801.h"
		; -include "include/boards/obi-jack.h"
		; -include "include/boards/room-sensor.h"
		; -include "include/boards/shelly1.h"
		; -include "include/boards/shellyi3.h"
		; -include "include/boards/test-device.h"
