#define IOT_NODE_TOSTRING(x) #x
#define IOT_NODE_STR(x) IOT_NODE_TOSTRING(x)

#define ARDUINO_SAMD_VARIANT_COMPLIANCE
#define FADE_LED_PWM_BITS 8
// #define NO_GLOBAL_MDNS
#define TAG_MHZ19 ""

#define IOT_NODE_ESP_NOW_WIFI_CHANNEL 14

#define IOT_NODE_BUILD_GIT_REV IOT_NODE_STR(IOT_NODE_ENV_BUILD_GIT_REV)
#define IOT_NODE_PIO_ENV IOT_NODE_STR(IOT_NODE_ENV_PIO_ENV)
#define IOT_NODE_PIO_PLATFORM IOT_NODE_STR(IOT_NODE_ENV_PIO_PLATFORM)
#define IOT_NODE_PIO_FRAMEWORK IOT_NODE_STR(IOT_NODE_ENV_PIO_FRAMEWORK)
#define IOT_NODE_NAME IOT_NODE_STR(IOT_NODE_ENV_NAME)
#define IOT_NODE_OTA_PASSWORD IOT_NODE_STR(IOT_NODE_ENV_OTA_PASSWORD)
